import type { Metadata } from "next";
import { Geist, Geist_Mono, Oswald } from "next/font/google"; // Import Oswald font
import "./globals.css";
import NavBar from "@/components/NavBar";
import { Analytics } from "@vercel/analytics/next"


// Add Oswald font
const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  weight: ["400", "700"], // Specify weights as needed
});

export const metadata: Metadata = {
  title: "Nishant Kumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${oswald.variable}`}
      >
        <NavBar/>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
